---
# Snowflake
image:
    file: .gitpod.Dockerfile

ports:
    - port: 8080
      onOpen: open-preview

tasks:
    - name: connect
# The private SSH key is stored in a single line as DBT_SNOWFLAKE_PRIVATE_KEY.
# Unfortunately, Snowflake will only accept the key if it is multi-line.
# The sed command transforms the key
# and then stores it as a file, which can be processed by Snowflake.
      command: |
          dbt debug
          dbt deps
      openMode: split-left
    - name: generate docs
      command: |
          dbt docs generate
          dbt docs serve --no-browser --port 8080
      openMode: split-right

vscode:
  extensions:
    - ms-python.python
    - innoverio.vscode-dbt-power-user
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow
    - samuelcolvin.jinjahtml

